on: 
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  training-pdf-builder:
    runs-on: ubuntu-latest
    name: Build the training PDF
    steps:
      - uses: actions/checkout@v2
      - uses: antaljanosbenjamin/compile-latex@v1.0.0
        with:
          file: master.tex
          args: -pdf -pdflatex="pdflatex -interaction=nonstopmode" -use-make
      - run: '(test -f master.pdf && echo PDF exists) || (echo PDF does not exist && exit 1)'
