name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  training-pdf-builder:
    runs-on: ubuntu-latest
    name: Build the training PDF and Release
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build PDF
        run: |
          nix-build

      - name: Update PDF name
        run: |
          cp result/master.pdf gravwell_training_${{ github.ref_name }}.pdf

      - name: Publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} gravwell_training_${{ github.ref_name }}.pdf --verify-tag --generate-notes
